name: Dataset Statistics

on: [push, pull_request]

jobs:
  dataset_statistics:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip list

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

    - name: Check data statistics & generate report
      run: |
        python -m mlops_groupp_66.dataset_statistics > data_statistics.md
        echo '![](./data_statistics.png "Data statistics")' >> data_statistics.md

    - name: Setup cml
      uses: iterative/setup-cml@v2

    - name: Comment on PR
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cml comment create data_statistics.md --watermark-title="Data Checker"
